name: "Offsite Feedback"
description: "Capture feedback about our recent team offsite"
title: "Offsite feedback - [your short summary]"
labels:
  - "Offsite Feedback"
assignees:
  - "CallMeGreg"
body:
  - type: input
    id: overall-rating
    attributes:
      label: "Overall Rating (1-10)"
      description: "Please rate the experience."
    validations:
      required: true

  - type: textarea
    id: what-went-well
    attributes:
      label: "What went well?"
      description: "Share what you found helpful or enjoyable."
    validations:
      required: false

  - type: textarea
    id: improvements
    attributes:
      label: "What could be improved?"
      description: "Suggest ideas for next time."
    validations:
      required: false

  - type: dropdown
    id: team
    attributes:
      label: "Team"
      description: "Which team are you part of?"
      options:
        - "Engineering"
        - "Product"
        - "Design"
    validations:
      required: true
